#need super user permission
sudo: required

#pre-install these services
services:
  - docker

#series of command before the test is run.
before_install:
  - docker build -t fredjackyong97/docker-react -f Dockerfile.dev  .

#any command that is required to be run in order to run the test  
script:
  - docker run -e CI=true fredjackyong97/docker-react npm run test